using System;
using System.Threading;

namespace GridChallenge
{
    // This class is used due to way that Random numbers are generated by using the clock thread. This allows me to have random numbers when iteratively creating instances.
    /// <summary>
    /// Creates a completely static number, regardless of the current clock thread.
    /// </summary>
    public static class StaticRandom
    {
        private static int seed;

        private static ThreadLocal<Random> threadLocal = new ThreadLocal<Random>
            (() => new Random(Interlocked.Increment(ref seed)));

        static StaticRandom()
        {
            seed = Environment.TickCount;
        }

        public static Random Instance { get { return threadLocal.Value; } }
    }
}
